"""empty message

Revision ID: 021181231a70
Revises: dbdb901bb876
Create Date: 2023-09-23 16:05:59.446482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021181231a70'
down_revision = 'dbdb901bb876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('expense_currency', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('current_currency', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_currency')
    op.drop_column('expense', 'expense_currency')
    # ### end Alembic commands ###
