"""empty message

Revision ID: 0a9254191554
Revises: 1d146ac1657b
Create Date: 2023-12-25 19:46:07.774663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9254191554'
down_revision = '1d146ac1657b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('expense_group_id_fkey', 'expense', type_='foreignkey')
    op.create_foreign_key(None, 'expense', 'group', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('expense_snapshot_expense_id_fkey', 'expense_snapshot', type_='foreignkey')
    op.create_foreign_key(None, 'expense_snapshot', 'expense', ['expense_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('friend_request_sender_id_fkey', 'friend_request', type_='foreignkey')
    op.drop_constraint('friend_request_receiver_id_fkey', 'friend_request', type_='foreignkey')
    op.create_foreign_key(None, 'friend_request', 'user', ['receiver_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'friend_request', 'user', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('group_user_id_fkey', 'group', type_='foreignkey')
    op.create_foreign_key(None, 'group', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_login_user_id_fkey', 'user_login', type_='foreignkey')
    op.create_foreign_key(None, 'user_login', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_login', type_='foreignkey')
    op.create_foreign_key('user_login_user_id_fkey', 'user_login', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.create_foreign_key('group_user_id_fkey', 'group', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'friend_request', type_='foreignkey')
    op.drop_constraint(None, 'friend_request', type_='foreignkey')
    op.create_foreign_key('friend_request_receiver_id_fkey', 'friend_request', 'user', ['receiver_id'], ['id'])
    op.create_foreign_key('friend_request_sender_id_fkey', 'friend_request', 'user', ['sender_id'], ['id'])
    op.drop_constraint(None, 'expense_snapshot', type_='foreignkey')
    op.create_foreign_key('expense_snapshot_expense_id_fkey', 'expense_snapshot', 'expense', ['expense_id'], ['id'])
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.create_foreign_key('expense_group_id_fkey', 'expense', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###
