"""empty message

Revision ID: 4051532683cb
Revises: 9a759a7b824b
Create Date: 2023-09-23 15:48:06.655348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4051532683cb'
down_revision = '9a759a7b824b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_user_name_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_user_name_key', 'user', ['user_name'])
    # ### end Alembic commands ###
