"""empty message

Revision ID: 4fa947b82db5
Revises: c00e4280fc17
Create Date: 2023-09-23 16:00:24.988398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa947b82db5'
down_revision = 'c00e4280fc17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('expense_expense_currency_fkey', 'expense', type_='foreignkey')
    op.drop_column('expense', 'expense_currency')
    op.drop_constraint('user_current_currency_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['user_name'])
    op.drop_column('user', 'current_currency')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_currency', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_current_currency_key', 'user', ['current_currency'])
    op.add_column('expense', sa.Column('expense_currency', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key('expense_expense_currency_fkey', 'expense', 'user', ['expense_currency'], ['current_currency'])
    # ### end Alembic commands ###
