"""empty message

Revision ID: 5f4fd5ec8917
Revises: 67b91a0cd9f8
Create Date: 2023-09-04 21:52:35.574616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f4fd5ec8917'
down_revision = '67b91a0cd9f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_tag', sa.String(length=30), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('expense_currency', sa.String(length=50), nullable=True),
    sa.Column('expense_description', sa.String(length=256), nullable=True),
    sa.Column('expense_image', sa.String(length=256), nullable=True),
    sa.Column('expense_category', sa.String(length=50), nullable=True),
    sa.Column('expense_comment', sa.String(length=256), nullable=True),
    sa.Column('payer', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('payee', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['expense_currency'], ['user.current_currency'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('expense_snapshots', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense_snapshot')
    op.drop_table('expense')
    # ### end Alembic commands ###
