"""empty message

Revision ID: 67b91a0cd9f8
Revises: 4db1c5765746
Create Date: 2023-09-04 21:50:02.085782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67b91a0cd9f8'
down_revision = '4db1c5765746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense_snapshot')
    op.drop_table('expense')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_snapshot',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('expense_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expense_snapshots', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], name='expense_snapshot_expense_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='expense_snapshot_pkey')
    )
    op.create_table('expense',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('expense_tag', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('total_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('expense_currency', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('expense_description', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('expense_image', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('expense_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('expense_comment', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('payer', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), autoincrement=False, nullable=True),
    sa.Column('payee', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['expense_currency'], ['user.current_currency'], name='expense_expense_currency_fkey'),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name='expense_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='expense_pkey')
    )
    # ### end Alembic commands ###
