"""empty message

Revision ID: c00e4280fc17
Revises: 4051532683cb
Create Date: 2023-09-23 15:51:28.147123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00e4280fc17'
down_revision = '4051532683cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
