"""empty message

Revision ID: dbdb901bb876
Revises: 4fa947b82db5
Create Date: 2023-09-23 16:00:57.537314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbdb901bb876'
down_revision = '4fa947b82db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
